---
main_user: celebrian
main_comment: 'Celebrian - Per-Kristian'
main_uid: 75321

# grog.package
package_list:
  - name: ansible
  - name: bash-completion
  - name: curl
  - name: git
  - name: git-crypt
  - name: net-tools
  - name: openssh-server
  - name: python3
  - name: screen
  - name: sshpass
  - name: sudo
  - name: tmux
  - name: tree
  - name: vim
  - name: wget

# geerlingguy.ntp
ntp_timezone: Europe/Oslo

# docker_install
docker_user: "{{ main_user }}"

# hardening
hardening_allow_users: "{{ main_user }}"

# ssh_port_change
ssh_port_change_dir: /etc/ssh/sshd_config.d/hardened.conf
