---
- name: First time ubuntu setup
  hosts: all
  become: True
  tasks:
    - name: Create main user
      user:
        name: celebrian
        append: True
        comment: 'Celebrian - Per-Kristian'
        groups: admin,sudo
        uid: "{{ celebrian_uid }}"
        update_password: on_create

    - name: Add authorized keys
      authorized_key:
        user: celebrian
        state: present
        key: https://github.com/celebrian.keys
