---
- name: First time ubuntu setup
  hosts: all
  become: True
  tasks:
    - name: Create main user
      user:
        name: {{ main_user }}
        shell: /bin/bash
        append: True
        comment: {{ main_comment }}
        groups: admin,sudo
        uid: "{{ main_uid }}"
        update_password: on_create

    - name: Add authorized keys
      authorized_key:
        user: {{ main_user }}
        state: present
        key: https://github.com/celebrian.keys
