---
- name: Setup infrastructure
  hosts: all 
  gather_facts: True
  vars_files: secrets/variables.yml
  tasks:
    - name: Install default packages
      include_role:
        name: grog.package
      vars: 
        - ansible_become: True

    - name: Install dotfiles
      include_role:
        name: geerlingguy.dotfiles

    - name: Basic SSH hardening
      include_role:
        name: geerlingguy.security
      vars: 
        - ansible_become: True

    - name: Advanced SSH hardening
      include_role:
        name: ssh_hardening
      vars: 
        - ansible_become: True

    - name: Remove MOTD spam on ubuntu machines
      become: True
      file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      loop:
        - 10-help-text
        - 50-landscape-sysinfo
        - 50-motd-news
        - 85-fwupd
        - 95-hwe-eol
      when: ansible_distribution == 'Ubuntu'

- name: Setup bastion spesific config
  hosts: bastion
  tasks:
    - name: install docker
      include_role:
        name: docker_install
      vars:
        - ansible_become: True

    - name: Set hostname
      become: True
      hostname:
        name: bastion