# grog.package
package_list_host:
  - wireguard-tools

# geerlingguy.security
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_autoupdate_enabled: false
security_fail2ban_enabled: true
